library(shiny)
library(shinydashboard)
iatResponses <- list("Not Applicable" = 0,
                     "Rarely" = 1,
                     "Occasionally" = 2,
                     "Frequently" = 3,
                     "Often" = 4,
                     "Always" = 5)
psqResponses <- list("Never" = 1,
                     "Occasionally" = 2,
                     "Frequently" = 3,
                     "Often" = 4,
                     "Always" = 5)
erqResponses <- list("Strongly Disagree" = 1,
                     "Moderately Disagree" = 2,
                     "Slightly Disagree" = 3,
                     "Neutral" = 4,
                     "Slightly Agree" = 5,
                     "Moderately Agree" = 6,
                     "Strongly Agree" = 7)
prqcResponses <- list("Never" = 1,
                      "Once in a while" = 2,
                      "Pretty often" = 3,
                      "Very often" = 4)
source("helpers.R")
source("global.R")


dashboardPage(
    dashboardHeader(titleWidth = 500,
                    title = "Detecting Early Indicators of Internet Addiction"),
    dashboardSidebar(
        width = 300,
        sidebarMenu(
            menuItem("Introduction", tabName = "intro"),
            menuItem("Internet Addiction Test", tabName = "iat"),
            menuItem("Parent-Child Internet Addiction Test", tabName = "pciat"),
            menuItem("Parenting Style Questionnaire", tabName = "psq"),
            menuItem("Emotional Regulation Questionnaire", tabName = "erq"),
            menuItem("Peer Relations Questionnaire for Children", tabName = "prqc"),
            menuItem("Results", tabName = "results")
        )
    ),
    dashboardBody(
        useShinyjs(),
        tabItems(
            tabItem("intro", 
                    fluidRow(
                        box(width = 12, status = "info",
                            title = "Detecting Early Indicators of Internet Addiction",
                            "Recent work in the psychological literature suggests that the risks of Internet ",
                            "Addiction in adolescents and young adults may appear as early as in childhood ",
                            "from their parents. This web-application presents some useful tools to identify ",
                            "early indicators of Internet Addiction. ",
                            tags$br(),tags$br(),
                            "Take the Internet Addiction Test or the Parent-Child Internet Addiction Test ",
                            "to determine if you or your child show signs of Internet Addiction. If you may ",
                            "be at risk, the following questionnaires may help you determine what factors ",
                            "contribute to the increased likelihood of Internet Addiction.",
                            tags$br(),tags$br(),
                            "After filling out the appropriate questionnaires, click the Results tab to ",
                            "see what the questionnaires say!",
                            tags$br(),tags$br(),
                            tags$em("*These tests are not meant for diagnostic purposes.")
                        )
                    )
            ),
            tabItem("iat", 
                    fluidRow(
                        box(width = 12, status = "info",
                            title = "Internet Addiction Test",
                            "This Internet addiction screening test can help determine whether ",
                            "you might be spending way too much time on the Internet (to the ",
                            "point where your internet use is impacting various areas of your life). ",
                            "Use the results to decide if you need to see a doctor or other mental ",
                            "health professional to further discuss your addictive use of the Internet.", 
                            tags$br(), tags$br(),
                            "*Internet addiction is not a psychiatric disorder as defined by the DSM IV.",
                            tags$br(), tags$br(),
                            tags$b("Instructions: "),
                            "This 20-item questionnaire measures mild, moderate, and severe levels of ",
                            "Internet Addiction. To assess your level of addiction to the Internet, ",
                            "answer the following questions."
                        ),
                        box(width = 12, status = "info",
                            radioButtons("iat_1", 
                                         label = tags$h5("1. How often do you find that you stay on-line longer than you intended?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("iat_2", 
                                         label = tags$h5("2. How often do you neglect household chores to spend more time on-line?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("iat_3", 
                                         label = tags$h5("3. How often do you prefer the excitement of the Internet to intimacy with your partner?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("iat_4", 
                                         label = tags$h5("4. How often do you form new relationships with fellow on-line users?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("iat_5", 
                                         label = tags$h5("5. How often do others in your life complain to you about the amount of time you spend on-line?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("iat_6", 
                                         label = tags$h5("6. How often do your grades or school work suffer because of the amount of time you spend on-line?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("iat_7", 
                                         label = tags$h5("7. How often do you check your e-mail before something else that you need to do?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("iat_8", 
                                         label = tags$h5("8. How often does your job performance or productivity suffer because of the Internet?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("iat_9", 
                                         label = tags$h5("9. How often do you become defensive or secretive when anyone asks you what you do on-line?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("iat_10", 
                                         label = tags$h5("10. How often do you block out disturbing thoughts about your life with soothing thoughts of the Internet?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("iat_11", 
                                         label = tags$h5("11. How often do you find yourself anticipating when you will go on-line again?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("iat_12", 
                                         label = tags$h5("12. How often do you fear that life without the Internet would be boring, empty, and joyless?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("iat_13", 
                                         label = tags$h5("13. How often do you snap, yell, or act annoyed if someone bothers you while you are on-line?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("iat_14", 
                                         label = tags$h5("14. How often do you lose sleep due to late-night log-ins?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("iat_15", 
                                         label = tags$h5("15. How often do you feel preoccupied with the Internet when off-line, or fantasize about being on-line?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("iat_16", 
                                         label = tags$h5("16. How often do you find yourself saying \"just a few more minutes\" when on-line?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("iat_17", 
                                         label = tags$h5("17. How often do you try to cut down the amount of time you spend on-line and fail?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("iat_18", 
                                         label = tags$h5("18. How often do you try to hide how long you've been on-line?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("iat_19", 
                                         label = tags$h5("19. How often do you choose to spend more time on-line over going out with others?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("iat_20", 
                                         label = tags$h5("20. How often do you feel depressed, moody, or nervous when you are off-line, which goes away once you are back on-line?"),
                                         choices = iatResponses, 
                                         selected = character(0))
                        )
                    ),
                    
                    withBusyIndicatorUI(
                        actionButton(
                            "iat_submit",
                            "Submit",
                            class = "btn-primary"
                        )
                    ),
                    tags$br(),
                    
                    "Young, K. S. (1998) Internet addiction:  The emergence of a new clinical disorder. ",
                    tags$em("CyberPsychology and Behavior, 1(3)"), ", 237-244.",
                    tags$em("Adapted from "), 
                    tags$a(href = "https://www.healthyplace.com/psychological-tests/internet-addiction-test/",
                           "Healthy Place"),
                    tags$br()
            ),
            tabItem("pciat", 
                    fluidRow(
                        box(
                            width = 12, status = "info",
                            title = "Parent-Child Internet Addiction Test",
                            "How do you know if your child may be addicted to the Internet? Many parents at ",
                            "least ask their children how much time they're spending on the Internet. Trouble ",
                            "is, most kids are apt to lie, especially if they\'re already addicted. If the ",
                            "computer is in their room, you have no way of knowing the truth. The following ",
                            "test may help you determine if you are dealing with Internet addiction in your home.",
                            tags$br(), tags$br(),
                            "*Internet addiction is not a psychiatric disorder as defined by the DSM IV.",
                            tags$br(), tags$br(),
                            tags$b("Instructions: "),
                            "This 20-item questionnaire measures mild, moderate, and severe levels of Internet ",
                            "Addiction. To assess your child's level of addiction to the Internet, answer the ",
                            "following questions. Remember, when answering, only consider time your child uses ",
                            "the Internet for non-academic purposes."
                        ),
                        box(width = 12, status = "info",
                            radioButtons("pciat_1", 
                                         label = tags$h5("1. How often does your child disobey time limits you set for on-line use?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("pciat_2", 
                                         label = tags$h5("2. How often does your child neglect household chores to spend more time on-line?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("pciat_3", 
                                         label = tags$h5("3. How often does your child prefer to spend time on-line rather than with the rest of your family?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("pciat_4", 
                                         label = tags$h5("4. How often does your child form new relationships with fellow on-line users?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("pciat_5", 
                                         label = tags$h5("5. How often do you complain about the amount of time your child spends on-line?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("pciat_6", 
                                         label = tags$h5("6. How often do your child's grades suffer because of the amount of time he or she spends on-line?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("pciat_7", 
                                         label = tags$h5("7. How often does your child check his or her e-mail before doing something else?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("pciat_8", 
                                         label = tags$h5("8. How often does your child seem withdrawn from others since discovering the Internet?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("pciat_9", 
                                         label = tags$h5("9. How often does your child become defensive or secretive when asked what he or she does on-line?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("pciat_10", 
                                         label = tags$h5("10. How often have you caught your child sneaking on-line against your wishes?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("pciat_11", 
                                         label = tags$h5("11. How often does your child spend time alone in his or her room playing on the computer?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("pciat_12", 
                                         label = tags$h5("12. How often does your child receive strange phone calls from new \"on-line\" friends?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("pciat_13", 
                                         label = tags$h5("13. How often does your child snap, yell, or act annoyed if bothered while on-line?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("pciat_14", 
                                         label = tags$h5("14. How often does your child seem more tired and fatigued than he or she did before the Internet came along?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("pciat_15", 
                                         label = tags$h5("15. How often does your child seem preoccupied with being back on-line when off-line?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("pciat_16", 
                                         label = tags$h5("16. How often does your child throw tantrums with your interference about how long he or she spends on-line?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("pciat_17", 
                                         label = tags$h5("17. How often has your child choose to spend time on-line rather than doing once enjoyed hobbies and/or outside interests?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("pciat_18", 
                                         label = tags$h5("18. How often does your child become angry or belligerent when you place time limits on how much time he or she is allowed to spend on-line?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("pciat_19", 
                                         label = tags$h5("19. How often does your child choose to spend more time on-line than going out with friends?"),
                                         choices = iatResponses, 
                                         selected = character(0)),
                            radioButtons("pciat_20", 
                                         label = tags$h5("20. How often does your child feel depressed, moody, or nervous when off-line which seems to goes away once back on-line?"),
                                         choices = iatResponses, 
                                         selected = character(0))
                        )
                    ),
                    
                    withBusyIndicatorUI(
                        actionButton(
                            "pciat_submit",
                            "Submit",
                            class = "btn-primary"
                        )
                    ),
                    tags$br(),
                    
                    "Young, K. S. (2004). Parent-child Internet addiction test [Online]. Available: http://netaddiction.com/resources/parents_test.htm.",
                    tags$br(),
                    tags$em("Adapted from "), 
                    tags$a(href = "https://www.healthyplace.com/psychological-tests/internet-addiction-test/",
                           "Healthy Place"),
                    tags$br()
            ),
            tabItem("psq", 
                    fluidRow(
                        box(
                            width = 12, status = "info",
                            title = "Parenting Style Questionnaire",
                            tags$b("Instructions: "),
                            "Please rate how often you engage in the different parenting practices, listed below. ",
                            "Scores range from \"Never\" to \"Always\" on a 5-point scale."
                        ),
                        box(width = 12, status = "info",
                            radioButtons("psq_1", 
                                         label = tags$h5("1. I am responsive to my child's feelings and needs:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_2", 
                                         label = tags$h5("2. I take my child's wishes into consideration before I ask him/her to do something:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_3", 
                                         label = tags$h5("3. I explain to my child how I feel about his/her good/bad behaviour:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_4", 
                                         label = tags$h5("4. I encourage my child to talk about his/her feelings and problems:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_5", 
                                         label = tags$h5("5. I encourage my child to freely \"speak his/her mind\", even if he/she disagrees with me:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_6", 
                                         label = tags$h5("6. I explain the reasons behind my expectations:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_7", 
                                         label = tags$h5("7. I provide comfort and understanding when my child is upset:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_8", 
                                         label = tags$h5("8. I compliment my child"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_9", 
                                         label = tags$h5("9. I consider my child's preferences when I make plans for the family (e.g., weekends away and holidays):"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_10", 
                                         label = tags$h5("10. I respect my child's opinion and encourage him/her to express them:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_11", 
                                         label = tags$h5("11. I treat my child as an equal member of the family:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_12", 
                                         label = tags$h5("12. I provide my child reasons for the expectations I have for him/her:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_13", 
                                         label = tags$h5("13. I have warm and intimate times together with my child:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_14", 
                                         label = tags$h5("14. When my child asks me why he/she has to do something I tell him/her it is because I said so, I am your parent, or because that is what I want:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_15", 
                                         label = tags$h5("15. I punish my child by taking privileges away from him/her (e.g., TV, games, visiting friends):"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_16", 
                                         label = tags$h5("16. I yell when I disapprove of my child's behaviour:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_17", 
                                         label = tags$h5("17. I explode in anger towards my child:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_18", 
                                         label = tags$h5("18. I spank my child when I don't like what he/she does or says:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_19", 
                                         label = tags$h5("19. I use criticism to make my child improve his/her behaviour:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_20", 
                                         label = tags$h5("20. I use threats as a form of punishment with little or no justification:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_21", 
                                         label = tags$h5("21. I punish my child by withholding emotional expressions (e.g., kisses and cuddles):"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_22", 
                                         label = tags$h5("22. I openly criticise my child when his/her behaviour does not meet my expectations:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_23", 
                                         label = tags$h5("23. I find myself struggling to try to change how my child thinks or feels about things:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_24", 
                                         label = tags$h5("24. I feel the need to point out my child's past behavioural problems to make sure he/she will not do them again:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_25", 
                                         label = tags$h5("25. I remind my child that I am his/her parent:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_26", 
                                         label = tags$h5("26. I remind my child of all the things I am doing and I have done for him/her:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_27", 
                                         label = tags$h5("27. I find it difficult to discipline my child:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_28", 
                                         label = tags$h5("28. I give into my child when he/she causes a commotion about something:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_29", 
                                         label = tags$h5("29. I spoil my child:"),
                                         choices = psqResponses, 
                                         selected = character(0)),
                            radioButtons("psq_30", 
                                         label = tags$h5("30. I ignore my child's bad behaviour:"),
                                         choices = psqResponses, 
                                         selected = character(0))
                        )
                    ),
                    
                    withBusyIndicatorUI(
                        actionButton(
                            "psq_submit",
                            "Submit",
                            class = "btn-primary"
                        )
                    ),
                    tags$br(),
                    
                    "Based on Robinson, C., Mandleco, B., Olsen, S. F., & Hart, C. H. (1995). Authoritative, authoritarian, and ",
                    "permissive parenting practices: Development of a new measure. ",
                    tags$em("Psychological Reports, 77, "),
                    "819-830.",
                    tags$br()
            ),
            tabItem("erq", 
                    fluidRow(
                        box(
                            width = 12, status = "info",
                            title = "Emotional Regulation Questionnaire",
                            "The questions below involve two distinct aspects of your emotional life. One ",
                            "is your emotional experience, or what you feel like inside. The other is your ",
                            "emotional expression, or how you show your emotions in the way you talk, gesture, ",
                            "or behave. Although some of the following questions may seem similar to one another, ",
                            "they differ in important ways. ",
                            tags$br(), tags$br(),
                            tags$b("Instructions: "),
                            "For each item, please answer using the scale from strongly disagree to agree:"
                        ),
                        box(width = 12, status = "info",
                            radioButtons("erq_1", 
                                         label = tags$h5("1. When I want to feel more positive emotion (such as joy or amusement), I change what I'm thinking about. "),
                                         choices = erqResponses, 
                                         selected = character(0)),
                            radioButtons("erq_2", 
                                         label = tags$h5("2. I keep my emotions to myself. "),
                                         choices = erqResponses, 
                                         selected = character(0)),
                            radioButtons("erq_3", 
                                         label = tags$h5("3. When I want to feel less negative emotion (such as sadness or anger), I change what I'm thinking about. "),
                                         choices = erqResponses, 
                                         selected = character(0)),
                            radioButtons("erq_4", 
                                         label = tags$h5("4. When I am feeling positive emotions, I am careful not to express them. "),
                                         choices = erqResponses, 
                                         selected = character(0)),
                            radioButtons("erq_5", 
                                         label = tags$h5("5. When I'm faced with a stressful situation, I make myself think about it in a way that helps me stay calm."),
                                         choices = erqResponses, 
                                         selected = character(0)),
                            radioButtons("erq_6", 
                                         label = tags$h5("6. I control my emotions by not expressing them. "),
                                         choices = erqResponses, 
                                         selected = character(0)),
                            radioButtons("erq_7", 
                                         label = tags$h5("7. When I want to feel more positive emotion, I change the way I'm thinking about the situation. "),
                                         choices = erqResponses, 
                                         selected = character(0)),
                            radioButtons("erq_8", 
                                         label = tags$h5("8. I control my emotions by changing the way I think about the situation I'm in. "),
                                         choices = erqResponses, 
                                         selected = character(0)),
                            radioButtons("erq_9", 
                                         label = tags$h5("9. When I am feeling negative emotions, I make sure not to express them. "),
                                         choices = erqResponses, 
                                         selected = character(0)),
                            radioButtons("erq_10", 
                                         label = tags$h5("10. When I want to feel less negative emotion, I change the way I'm thinking about the situation."),
                                         choices = erqResponses, 
                                         selected = character(0))
                            
                        )
                    ),
                    
                    withBusyIndicatorUI(
                        actionButton(
                            "erq_submit",
                            "Submit",
                            class = "btn-primary"
                        )
                    ),
                    tags$br(),
                    
                    "Based on Gross, J. J., & John, O. P. (2003). Individual differences in two emotion regulation ",
                    "processes: Implications for affect, relationships, and well-being. ",
                    tags$em("Journal of Personality and Social Psychology, 85, "), "348-362.",
                    tags$br()
            ),
            tabItem("prqc", 
                    fluidRow(
                        box(
                            width = 12, status = "info",
                            title = "Peer Relations Questionnaire for Children",
                            tags$b("Instructions: "),
                            "Show how often the following statements are true of you. To do this choose one of ",
                            "the answers underneath each statement."
                        ),
                        box(width = 12, status = "info",
                            radioButtons("prqc_1", 
                                         label = tags$h5("1. I like playing sport "),
                                         choices = prqcResponses, 
                                         selected = character(0)),
                            radioButtons("prqc_2", 
                                         label = tags$h5("2. I get good marks in class "),
                                         choices = prqcResponses, 
                                         selected = character(0)),
                            radioButtons("prqc_3", 
                                         label = tags$h5("3. I get called names by others"),
                                         choices = prqcResponses, 
                                         selected = character(0)),
                            radioButtons("prqc_4", 
                                         label = tags$h5("4. I give soft kids a hard time "),
                                         choices = prqcResponses, 
                                         selected = character(0)),
                            radioButtons("prqc_5", 
                                         label = tags$h5("5. I like to make friends "),
                                         choices = prqcResponses, 
                                         selected = character(0)),
                            radioButtons("prqc_6", 
                                         label = tags$h5("6. I play up in class "),
                                         choices = prqcResponses, 
                                         selected = character(0)),
                            radioButtons("prqc_7", 
                                         label = tags$h5("7. I feel I can't trust others"),
                                         choices = prqcResponses, 
                                         selected = character(0)),
                            radioButtons("prqc_8", 
                                         label = tags$h5("8. I get picked on by others "),
                                         choices = prqcResponses, 
                                         selected = character(0)),
                            radioButtons("prqc_9", 
                                         label = tags$h5("9. I am part of a group that goes round teasing others "),
                                         choices = prqcResponses, 
                                         selected = character(0)),
                            radioButtons("prqc_10", 
                                         label = tags$h5("10. I like to help people are being harassed "),
                                         choices = prqcResponses, 
                                         selected = character(0)),
                            radioButtons("prqc_11", 
                                         label = tags$h5("11. I like to make others scared of me"),
                                         choices = prqcResponses, 
                                         selected = character(0)),
                            radioButtons("prqc_12", 
                                         label = tags$h5("12. Others leave me out of things on purpose "),
                                         choices = prqcResponses, 
                                         selected = character(0)),
                            radioButtons("prqc_13", 
                                         label = tags$h5("13. I get into fights at school "),
                                         choices = prqcResponses, 
                                         selected = character(0)),
                            radioButtons("prqc_14", 
                                         label = tags$h5("14. I like to show others that I'm the boss"),
                                         choices = prqcResponses, 
                                         selected = character(0)),
                            radioButtons("prqc_15", 
                                         label = tags$h5("15. I share things with others "),
                                         choices = prqcResponses, 
                                         selected = character(0)),
                            radioButtons("prqc_16", 
                                         label = tags$h5("16. I enjoy upsetting wimps"),
                                         choices = prqcResponses, 
                                         selected = character(0)),
                            radioButtons("prqc_17", 
                                         label = tags$h5("17. I like to get into a fight with someone I can easily beat "),
                                         choices = prqcResponses, 
                                         selected = character(0)),
                            radioButtons("prqc_18", 
                                         label = tags$h5("18. Others make fun of me "),
                                         choices = prqcResponses, 
                                         selected = character(0)),
                            radioButtons("prqc_19", 
                                         label = tags$h5("19. I get hit and pushed around by others "),
                                         choices = prqcResponses, 
                                         selected = character(0)),
                            radioButtons("prqc_20", 
                                         label = tags$h5("20. I enjoy helping others"),
                                         choices = prqcResponses, 
                                         selected = character(0))
                        )
                    ),
                    
                    withBusyIndicatorUI(
                        actionButton(
                            "prqc_submit",
                            "Submit",
                            class = "btn-primary"
                        )
                    ),
                    tags$br(),
                    
                    "Based on Rigby, K. & Slee, P. T. (1993) Dimensions of interpersonal relating among ",
                    "Australian school children and their implications for psychological wellbeing. ",
                    tags$em("Journal of Social Psychology, 133(1), "), "33-42. ",
                    tags$br()
            ),
            tabItem("results", 
                    fluidRow(
                        valueBox(textOutput("iat_scores"), width = 6, 
                                 "Internet Addiction Test", icon = icon("globe",lib="glyphicon")),
                        valueBox(textOutput("pciat_scores"), width = 6, 
                                 "Parent-Child Internet Addiction Test", icon = icon("globe",lib="glyphicon"))
                    ),
                    fluidRow(
                        box(width = 6, status = "info",
                            tags$b("0-19: "),
                            "You use the internet at a below-average frequency. You probably have good control over your usage.",
                            tags$br(), tags$br(),
                            tags$b("20-49: "),
                            "You are an average on-line user. You may surf the Web a bit too long at times, but you have control over your usage.",
                            tags$br(), tags$br(),
                            tags$b("50-79: "),
                            "You are experiencing occasional or frequent problems because of the Internet. You should consider their full impact on your life.",
                            tags$br(), tags$br(),
                            tags$b("80-100: "),
                            "Your Internet usage is causing significant problems in your life. You should evaluate the impact of the Internet on your life and address the problems directly caused by your Internet usage."
                        ),
                        box(width = 6, status = "info",
                            tags$b("0-19: "),
                            "Your child uses the internet at a below-average frequency. They probably have good control over their usage.",
                            tags$br(), tags$br(),
                            tags$b("20-49: "),
                            "Your child is an average on-line user. They may surf the Web a bit too long at times, but they have control over their usage.",
                            tags$br(), tags$br(),
                            tags$b("50-79: "),
                            "Your child is experiencing occasional or frequent problems because of the Internet. You should consider the internet's full impact on their life.",
                            tags$br(), tags$br(),
                            tags$b("80-100: "),
                            "Your child's Internet usage is causing significant problems in their life. You should evaluate the impact of the Internet on their life and address the problems directly caused by their Internet usage."
                        )
                    ),
                    fluidRow(
                        valueBox(textOutput("psq_score1"), width = 4, 
                                 "Parenting Style: Authoritative", icon = icon("home",lib="glyphicon")),
                        valueBox(textOutput("psq_score2"), width = 4, 
                                 "Parenting Style: Authoritarian", icon = icon("home",lib="glyphicon")),
                        valueBox(textOutput("psq_score3"), width = 4, 
                                 "Parenting Style: Permissive", icon = icon("home",lib="glyphicon"))
                    ),
                    fluidRow(
                        box(width = 12, status = "info",
                            "The highest score among the three categories corresponds most closely to your parenting style.",
                            tags$br(),tags$br(),
                            tags$b("Authoritative Parenting: "),
                            "Children who grow up with this style of parenting tend to have the most optimal long-term ",
                            "developmental outcomes, such as high competence, high self-confidence, and low tendency to ",
                            "engage in risky behavior. They are least likely to develop problems with Internet Addiction.",
                            tags$br(),tags$br(),
                            tags$b("Authoritarian Parenting: "),
                            "Children who grow up with this style of parenting tend to have fewer and weaker peer relationships ",
                            "and develop unhealthy self-regulation strategies as opposed to authoritative parenting. They also ",
                            "tend to have low self-esteem as they approach adolescence. Due to these qualities, they are higher ",
                            "in risk for Internet Addiction during adolescence and young adulthood.",
                            tags$br(),tags$br(),
                            tags$b("Permissive Parenting: "),
                            "Children who grow up with this style of parenting have a higher tendency to engage in risky ",
                            "behavior and lack self-regulation strategies. They tend to externalize emotions. Due to the lack of ",
                            "self regulatory behavior, they are higher in risk for developing Internet Addiction during ",
                            "adolescence and young adulthood."
                        )
                    ),
                    fluidRow(
                        valueBox(textOutput("erq_score1"), width = 6, 
                                 "Cognitive Reappraisal", icon = icon("exclamation")),
                        valueBox(textOutput("erq_score2"), width = 6, 
                                 "Expressive Suppression", icon = icon("exclamation"))
                    ),
                    fluidRow(
                        box(width = 12, status = "info",
                            "These scores are out of 10.",
                            tags$br(),tags$br(),
                            tags$b("Cognitive reappraisal "),
                            "is a promising type of emotion regulation because it is a particularly effective ",
                            "strategy for down-regulating negative emotion. For this reason, the ability to use ",
                            "reappraisal may serve as an important protective factor in the context of stress. ",
                            "In the context of Internet Addiction, effectively down-regulating the compulsive ",
                            "need to use the internet reduces the risk of addiction.",
                            tags$br(),tags$br(),
                            tags$b("Expressive Suppression "),
                            "is a response-focused strategy that intervenes once an emotion is already under way ",
                            "and after the behavioral responses have already been fully generated. It requires the ",
                            "individual to effortfully manage emotional responses as they constantly occur. "
                        )
                    ),
                    fluidRow(
                        valueBox(textOutput("prqc_score1"), width = 4, 
                                 "Bully", icon = icon("comments")),
                        valueBox(textOutput("prqc_score2"), width = 4, 
                                 "Victim", icon = icon("comments")),
                        valueBox(textOutput("prqc_score3"), width = 4, 
                                 "Pro Social", icon = icon("comments"))
                    ),
                    fluidRow(
                        box(width = 12, status = "info",
                            "These scores are out of 10.",
                            tags$br(),tags$br(),
                            "Both being a ", tags$b("bully"), "and a ", tags$b("victim"),
                            "have a negative impact on the child's peer relationships. Identifying with ",
                            "either is associated with higher risk of Internet Addiction. "
                        )
                    )
            )
        )
    )
)